### ISSUE TITLE
Attempted to add a trail vertex in between two previous vertices

### ISSUE THREAD

**Issue by jespertheend** [jespertheend/splix#43]
The server crashes frequently with the following stack trace:
```
error: Uncaught Error: Assertion failed: Attempted to add a trail vertex in between two previous vertices.
    at Player.#addTrailVertex (file:///home/runner/work/splix/splix/gameServer/src/gameplay/Player.js:354:13)
    at Player.#drainMovementQueue (file:///home/runner/work/splix/splix/gameServer/src/gameplay/Player.js:313:25)
    at Player.loop (file:///home/runner/work/splix/splix/gameServer/src/gameplay/Player.js:556:29)
    at Game.loop (file:///home/runner/work/splix/splix/gameServer/src/gameplay/Game.js:59:11)
    at ApplicationLoop.loop (file:///home/runner/work/splix/splix/gameServer/src/ApplicationLoop.js:15:26)
    at Object.action (ext:deno_web/02_timers.js:146:11)
    at handleTimerMacrotask (ext:deno_web/02_timers.js:63:10)
```

It also frequently logs a similar stack trace, though in this case the server doesn't crash because errors inside the message handler are always caught.
```
An error occurred while handling a websocket message ArrayBuffer {} Error: Assertion failed: Attempted to add a trail vertex in between two previous vertices.
    at Player.#addTrailVertex (file:///home/runner/work/splix/splix/gameServer/src/gameplay/Player.js:354:13)
    at Player.#drainMovementQueue (file:///home/runner/work/splix/splix/gameServer/src/gameplay/Player.js:313:25)
    at Player.clientPosUpdateRequested (file:///home/runner/work/splix/splix/gameServer/src/gameplay/Player.js:269:27)
    at WebSocketConnection.onMessage (file:///home/runner/work/splix/splix/gameServer/src/WebSocketConnection.js:245:17)
    at WebSocket.<anonymous> (file:///home/runner/work/splix/splix/gameServer/src/WebSocketManager.js:23:24)
    at innerInvokeEventListeners (ext:deno_web/02_event.js:783:7)
    at invokeEventListeners (ext:deno_web/02_event.js:823:5)
    at dispatch (ext:deno_web/02_event.js:692:9)
    at WebSocket.dispatchEvent (ext:deno_web/02_event.js:1082:12)
    at WebSocket.[[[eventLoop]]] (ext:deno_websocket/01_websocket.js:433:16)
```

**Comment by jespertheend** [comment]
This may have been fixed in #41

**Comment by jespertheend** [comment]
Seems like this is still an issue, though less frequently.
The stack trace is different though.
```
Oct 21 18:17:07 splix-fra splixGameServer[506574]: error: Uncaught Error: Assertion failed: Attempted to add a trail vertex in between two previous vertices.
Oct 21 18:17:07 splix-fra splixGameServer[506574]:     at Player.#addTrailVertex (file:///home/runner/work/splix/splix/gameServer/src/gameplay/Player.js:390:13)
Oct 21 18:17:07 splix-fra splixGameServer[506574]:     at Player.#updateCurrentTile (file:///home/runner/work/splix/splix/gameServer/src/gameplay/Player.js:932:25)
Oct 21 18:17:07 splix-fra splixGameServer[506574]:     at Player.loop (file:///home/runner/work/splix/splix/gameServer/src/gameplay/Player.js:588:28)
Oct 21 18:17:07 splix-fra splixGameServer[506574]:     at Game.loop (file:///home/runner/work/splix/splix/gameServer/src/gameplay/Game.js:59:11)
Oct 21 18:17:07 splix-fra splixGameServer[506574]:     at ApplicationLoop.loop (file:///home/runner/work/splix/splix/gameServer/src/ApplicationLoop.js:15:26)
Oct 21 18:17:07 splix-fra splixGameServer[506574]:     at Object.action (ext:deno_web/02_timers.js:151:11)
Oct 21 18:17:07 splix-fra splixGameServer[506574]:     at handleTimerMacrotask (ext:deno_web/02_timers.js:65:10)
Oct 21 18:17:07 splix-fra splixGameServer[506574]:     at eventLoopTick (ext:core/01_core.js:189:21)
```

**Comment by jespertheend** [comment]
A similar stack trace also crashes the server:
```
Oct 22 11:46:10 splix-fra splixGameServer[516222]: An error occurred while handling a websocket message ArrayBuffer { [Uint8Contents]: <01 03 00 82 00 54>, byteLength: 6 } Error: Assertion failed: Attempted to add a trail vertex in between two previous vertices.
Oct 22 11:46:10 splix-fra splixGameServer[516222]:     at Player.#addTrailVertex (file:///home/runner/work/splix/splix/gameServer/src/gameplay/Player.js:390:13)
Oct 22 11:46:10 splix-fra splixGameServer[516222]:     at Player.#drainMovementQueue (file:///home/runner/work/splix/splix/gameServer/src/gameplay/Player.js:338:25)
Oct 22 11:46:10 splix-fra splixGameServer[516222]:     at Player.clientPosUpdateRequested (file:///home/runner/work/splix/splix/gameServer/src/gameplay/Player.js:294:27)
Oct 22 11:46:10 splix-fra splixGameServer[516222]:     at WebSocketConnection.onMessage (file:///home/runner/work/splix/splix/gameServer/src/WebSocketConnection.js:271:17)
Oct 22 11:46:10 splix-fra splixGameServer[516222]:     at WebSocket.<anonymous> (file:///home/runner/work/splix/splix/gameServer/src/WebSocketManager.js:18:24)
Oct 22 11:46:10 splix-fra splixGameServer[516222]:     at innerInvokeEventListeners (ext:deno_web/02_event.js:750:7)
Oct 22 11:46:10 splix-fra splixGameServer[516222]:     at invokeEventListeners (ext:deno_web/02_event.js:797:5)
Oct 22 11:46:10 splix-fra splixGameServer[516222]:     at dispatch (ext:deno_web/02_event.js:654:9)
Oct 22 11:46:10 splix-fra splixGameServer[516222]:     at WebSocket.[[[eventLoop]]] (ext:deno_websocket/01_websocket.js:452:11)
Oct 22 11:46:10 splix-fra splixGameServer[516222]:     at eventLoopTick (ext:core/01_core.js:183:11)
```

**Comment by jespertheend** [comment]
Judging by the call stacks, there's currently two situations where this might happen:

- When entering your own area. Presumably because your land gets filled in with a slight delay, causing your player to suddenly be on one of its own tiles, so adding the `previousPosition` might not necessarily be a valid position.
https://github.com/jespertheend/splix/blob/83e3258ccca60135e3b78cc17f38c5c6fceb3533/gameServer/src/gameplay/Player.js#L1003
I think in this case it would be fine to just ignore the assertion. It might cause an unexpected trail but these vertices will likely already be in the players area anyway.

- When the player movement queue is handled:
https://github.com/jespertheend/splix/blob/83e3258ccca60135e3b78cc17f38c5c6fceb3533/gameServer/src/gameplay/Player.js#L365
In this case we should make sure the `checkNextMoveValidity()` takes the current trail into account and mark any such movements as invalid.
