### ISSUE TITLE
the tile points to a non existent player

### ISSUE THREAD

**Issue by jespertheend** [jespertheend/splix#44]
The server crashes with the following stack trace sometimes
```
error: Uncaught Error: Assertion failed, the tile points to a non existent player
    at Game.getTileTypeForMessage (file:///Users/Jesper/repositories/splix-gameserver/gameServer/src/gameplay/Game.js:193:10)
    at file:///Users/Jesper/repositories/splix-gameserver/gameServer/src/gameplay/Game.js:163:16
    at file:///Users/Jesper/repositories/splix-gameserver/gameServer/src/gameplay/Arena.js:155:21
    at compressTiles (file:///Users/Jesper/repositories/splix-gameserver/gameServer/src/util/util.js:164:12)
    at Arena.getChunk (file:///Users/Jesper/repositories/splix-gameserver/gameServer/src/gameplay/Arena.js:153:10)
    at Game.getArenaChunkForMessage (file:///Users/Jesper/repositories/splix-gameserver/gameServer/src/gameplay/Game.js:162:22)
    at Player.sendChunk (file:///Users/Jesper/repositories/splix-gameserver/gameServer/src/gameplay/Player.js:735:31)
    at Player.#sendRequiredEdgeChunks (file:///Users/Jesper/repositories/splix-gameserver/gameServer/src/gameplay/Player.js:723:9)
    at Player.#currentPositionChanged (file:///Users/Jesper/repositories/splix-gameserver/gameServer/src/gameplay/Player.js:649:31)
    at Player.loop (file:///Users/Jesper/repositories/splix-gameserver/gameServer/src/gameplay/Player.js:565:33)
```

**Comment by jespertheend** [comment]
I think #57 fixed this
